
name: Deploy

on:
  
  push:
    branches: [ main ]
    paths: [ 'src/**/.version' ]
  
  workflow_dispatch:

jobs:

  get_changes:

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2
    
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
          
      - run: |
          echo ${{ steps.files.outputs.all }}
      
      - run: |
          json='${{ steps.files.outputs.all }}'
          echo "$json" | jq -c '[ .[] | select(endswith("/.version")) ]'
          
      - id: set-matrix
        run: |
          json='${{ steps.files.outputs.all }}'
          var=$(echo "$json" | jq -c '[ .[] | select(endswith("/.version")) ]')
          echo "::set-output name=matrix::$(echo $var)"
        
      - run: echo ${{ steps.set-matrix.outputs.matrix }}
      
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  
  
  deploy:
    
    needs: get_changes
    runs-on: windows-latest
    
    strategy:
      matrix:
        changes: ${{ fromJson(needs.get_changes.outputs.matrix) }}

    steps:
    
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - id: path
      name: Create Path Variable
      run: |
        $var="`"$('${{ matrix.changes }}'.TrimEnd('./version'))`""
        echo "::set-output name=path::$(echo $var)"
        
      
    - run: echo ${{ steps.path.outputs.path }}
      
    - name: Restore dependencies
      run: dotnet restore ${{ steps.path.outputs.path }}
      
    - name: Build
      run: dotnet build ${{ steps.path.outputs.path }} --configuration Release --no-restore
    
