name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TESTS_PATH: 'tests'

jobs:
  test_dirs:
  
    runs-on: windows-latest

    steps:
    
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(Get-ChildItem -Path '${{ env.TESTS_PATH }}' -Recurse -Filter '*.csproj' | Select -Expand Directory | Resolve-Path -Relative | ConvertTo-Json -compress)"
    
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}


  tests:
    
    needs: test_dirs
    runs-on: windows-latest
    
    strategy:
      matrix:
        tests: ${{ fromJson(needs.test_dirs.outputs.matrix) }}

    steps:
    
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore '${{ matrix.tests }}'
    - name: Build
      run: dotnet build ${{ matrix.tests }} --configuration Release --no-restore
    - name: Test
      run: dotnet test ${{ matrix.tests }} --configuration Release --no-build --verbosity normal
        
