name: Run Tests

on:
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

env:
  TESTS_PATH: 'tests'
  DOTNET_VERSION: 3.1.414

jobs:

  test_dirs:
  
    runs-on: windows-latest

    steps:
    
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(ConvertTo-Json -Compress @(Get-ChildItem -Path '${{ env.TESTS_PATH }}' -Recurse -Filter '*.csproj' | Select -Expand Directory | Resolve-Path -Relative))"
      
      - name: Check outputs
        run: echo ${{ steps.set-matrix.outputs.matrix }}
          
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}


  tests:
    
    needs: test_dirs
    runs-on: windows-latest
    
    strategy:
      matrix:
        tests: ${{ fromJson(needs.test_dirs.outputs.matrix) }}

    steps:
    
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ DOTNET_VERSION }}

    - uses: actions/cache@v2
      with:
        path:
          ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ DOTNET_VERSION }}-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore '${{ matrix.tests }}'
    - name: Build
      run: dotnet build ${{ matrix.tests }} --configuration Release --no-restore
    - name: Test
      run: dotnet test ${{ matrix.tests }} --configuration Release --no-build --verbosity normal
      
      
  tests_success:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check tests matrix status
        if: ${{ needs.tests.result != 'success' }}
        run: exit 1
        
